"""all tables

Revision ID: 97c93e1e608b
Revises: 
Create Date: 2020-02-02 16:18:42.307946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97c93e1e608b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filiere',
    sa.Column('idFiliere', sa.Integer(), nullable=False),
    sa.Column('nomFiliere', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('idFiliere')
    )
    op.create_table('etudiant',
    sa.Column('idCarteEtu', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=64), nullable=True),
    sa.Column('prenom', sa.String(length=64), nullable=True),
    sa.Column('numeroEtudiant', sa.Integer(), nullable=True),
    sa.Column('typeContratEtudiant', sa.String(length=64), nullable=True),
    sa.Column('tarif', sa.Integer(), nullable=True),
    sa.Column('filiere', sa.Integer(), nullable=True),
    sa.Column('numeroTel', sa.Integer(), nullable=True),
    sa.Column('mailEtu', sa.String(length=64), nullable=True),
    sa.Column('mailEntreprise', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['filiere'], ['filiere.idFiliere'], ),
    sa.PrimaryKeyConstraint('idCarteEtu')
    )
    op.create_index(op.f('ix_etudiant_nom'), 'etudiant', ['nom'], unique=False)
    op.create_index(op.f('ix_etudiant_numeroEtudiant'), 'etudiant', ['numeroEtudiant'], unique=True)
    op.create_index(op.f('ix_etudiant_prenom'), 'etudiant', ['prenom'], unique=False)
    op.create_table('presence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matin', sa.Integer(), nullable=True),
    sa.Column('apresMidi', sa.Integer(), nullable=True),
    sa.Column('idCarteEtu', sa.Integer(), nullable=True),
    sa.Column('date', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idCarteEtu'], ['etudiant.idCarteEtu'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('presence')
    op.drop_index(op.f('ix_etudiant_prenom'), table_name='etudiant')
    op.drop_index(op.f('ix_etudiant_numeroEtudiant'), table_name='etudiant')
    op.drop_index(op.f('ix_etudiant_nom'), table_name='etudiant')
    op.drop_table('etudiant')
    op.drop_table('filiere')
    # ### end Alembic commands ###
